# Generated by Django 6.0.2 on 2026-02-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_affiliateclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateclick',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
