# Generated by Django 6.0.2 on 2026-04-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='affiliateclick',
            new_name='blog_affili_post_id_42dbea_idx',
            old_name='blog_affili_post_id_d17dc4_idx',
        ),
        migrations.RenameIndex(
            model_name='affiliateclick',
            new_name='blog_affili_session_3785b0_idx',
            old_name='blog_affili_session_4ae124_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_status_9deff2_idx',
            old_name='blog_post_status_701356_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_categor_4ee4b9_idx',
            old_name='blog_post_categor_7f0b6a_idx',
        ),
    ]
